# Site settings
title: Photos by Jimmac
description: I've been shooting photos for over 20 years now. These are some carefuly selected picks. To see more up to date photos, see my flickr and instagram feeds below.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://photos.jimmac.net" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url: 
gitlab_url: 
googleplus_url: 
instagram_url: https://instagram.com/jimmacfx_icons
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/jimmac
flickr_url: https://www.flickr.com/photos/jakubsteiner/

# Build settings
markdown: kramdown
